---
version: "3.5"
services:
  credits:
    build:
      dockerfile: Dockerfile.dev
    image: os_credits-dev:latest
    container_name: dev_os_credits
    networks:
      - credits
    env_file:
      - .env
    ports:
      - "8002:80"
    depends_on:
      - timescaledb
    volumes:
      - "./src:/code/src:ro"

  timescaledb:
    image: "timescale/timescaledb:2.11.2-pg14"
    container_name: dev_timescaledb
    command: postgres -c shared_preload_libraries=timescaledb
    networks:
      - credits
    env_file:
      - .env
    environment:
      - TIMESCALEDB_TELEMETRY=off
    expose:
      - "5432"
    volumes:
      - credits_data:/var/lib/postgresql/data
      - ./db_init:/docker-entrypoint-initdb.d

volumes:
  credits_data:
    external: false

networks:
  credits:
