---
version: "3.5"
services:
  credits:
    image: os_credits-dev:latest
    env_file:
      - .env
    environment:
      - MAIL_SMTP_SERVER=smtp_server
      - MAIL_NOT_STARTTLS=1
      - INFLUXDB_HOST=influxdb
    ports:
      - "8000:80"
    depends_on:
      - influxdb
      - smtp_server
    volumes:
      - "./src:/code/src:ro"

  influxdb:
    image: "influxdb:1.7-alpine"
    container_name: portal_influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_DB=credits_history
      - INFLUXDB_HTTP_AUTH_ENABLED=false
    healthcheck:
      test: wget http://localhost:8086/ping -qO /dev/null || return 1
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 5s

  smtp_server:
    image: "python:3.7-alpine"
    command: python3 -m smtpd -n -c DebuggingServer
    expose:
      - "25"
