[tool.poetry]
name = "os_credits"
version = "1.2.0"
description = ""
authors = ["gilbus"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "3.7.3"
aioinflux = "0.9.0"
aiohttp-swagger = "1.0.15"
prometheus_async = {version = "19.2",extras = ["aiohttp"]}
aiohttp_jinja2 = "1.1"
aiosmtplib = "1.1.4"
mypy_extensions = "0.4.3"

[tool.poetry.dev-dependencies]
aiohttp-devtools = "0.13.1"
pytest = "6.2.2"
pytest-aiohttp = "0.3.0"
pre-commit = "2.10.1"
black = {version = "20.8b1",allow-prereleases = true}
mypy = "0.800"
sphinx = "3.5.1"
sphinx-autodoc-typehints = "1.11.1"
pytest-localserver = "0.5.0"
pytest-cov = "2.11.1"
sphinxcontrib-trio = "1.1.2"
lxml = "4.6.2"
pytest-dotenv = "0.5.2"
sphinxcontrib-programoutput = "0.16"
docker-compose = "1.28.3"
pytest-black = "0.3.12"
pytest-mypy = "0.8.0"
pytest-flake8 = "1.0.7"
pytest-isort = "1.3.0"

[tool.poetry.scripts]
os-credits="os_credits.cli:main"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
