[tool.poetry]
name = "OS_project_usage_processor"
version = "0.1.0"
description = ""
authors = ["gilbus"]

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.5"
toml = "^0.10.0"

[tool.poetry.dev-dependencies]
mypy = "^0.660.0"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
