[tool.poetry]
name = "os_credits"
version = "1.1.0"
description = ""
authors = ["gilbus"]

[tool.poetry.dependencies]
python = "^3.9"
aiohttp = "3.8.1"
aioinflux = "0.9.0"
aiohttp-swagger = "1.0.16"
prometheus_async = {version = "22.1.0",extras = ["aiohttp"]}
aiohttp_jinja2 = "1.5"
aiosmtplib = "1.1.6"
mypy_extensions = "0.4.3"

[tool.poetry.dev-dependencies]
aiohttp-devtools = "1.0.post0"
pytest = "6.2.5"
pytest-aiohttp = "1.0.4"
pre-commit = "2.17.0"
black = {version = "22.1.0",allow-prereleases = true}
sphinx-autodoc-typehints = "1.17.0"
mypy = "0.931"
sphinx = "4.4.0"
pytest-localserver = "0.5.1.post0"
pytest-cov = "3.0.0"
sphinxcontrib-trio = "1.1.2"
lxml = "4.7.1"
pytest-dotenv = "0.5.2"
sphinxcontrib-programoutput = "0.17"
docker-compose = "1.29.2"
pytest-black = "0.3.12"
pytest-mypy = "0.9.1"
pytest-flake8 = "1.0.7"
pytest-isort = "2.0.0"

[tool.poetry.scripts]
os-credits="os_credits.cli:main"

[build-system]
requires = ["poetry>=1.1.4"]
build-backend = "poetry.masonry.api"
