name: build-image
on: pull_request
jobs:
    build-test:
        
        runs-on: ubuntu-latest
        steps:
            - name: Workflow run cleanup action
              uses: rokroskar/workflow-run-cleanup-action@v0.3.3
              env:
                GITHUB_TOKEN: "${{ secrets.GITHUBSECRET2 }}"
            - uses: actions/checkout@v4.1.7
            - name: Build with retry
              uses: Wandalen/wretry.action@v1.3.0
              with:
                command: docker build --no-cache  . 
                attempt_limit: 3
                attempt_delay: 5000
