name: Publish Docker
on:
  workflow_dispatch:
  push:
    branches:
      - 'staging'
      - 'dev'
      - 'hotfix/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow run cleanup action
        uses: rokroskar/workflow-run-cleanup-action@v0.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBSECRET2 }}

      - uses: actions/checkout@v3.4.0

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Set tag
        run: sed 's/\//-/g'  <<< "::set-output name=TAG::${{ steps.extract_branch.outputs.branch }}"
        id: tag

      - name: Get tag
        run: echo "The selected tag is ${{ steps.tag.outputs.TAG }}"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@3.04
        with:
          name: denbicloud/os_credits
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
          tags: ${{ steps.tag.outputs.TAG }}
          buildoptions: "--no-cache"
          attempt_limit: 3
          attempt_delay: 5000
